version: "3.9"

services:
  php:
    build: .
    volumes:
      - ./www/index.php:/var/www/index.php
      - ./php/php.ini:/usr/local/etc/php/php.ini
  #   # healthcheck:
  #   #   test: curl http://127.0.0.1:80/ | grep works || exit 1
  #   #   interval: 10s
  #   #   timeout: 1s
  #   #   retries: 5
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www/index.php:/var/www/index.php
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
