version: "3.9"

services:
  php:
    build: .
    volumes:
      - ./www/index.php:/var/www/index.php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    container_name: php
    healthcheck:
      test: curl nginx:80/ 2>&1 | grep works || exit 1
      interval: 3s
      timeout: 1s
      retries: 2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./www/index.php:/var/www/index.php
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
